version: "3.9"

services:
  bigtable:
    build:
      context: .
      dockerfile: config/docker/bigtable.dockerfile
    image: gleam-bigtable
    ports:
      - "9035:9035"
    restart: always

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: config/.env
    restart: always

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  db-data:
  redis-data:
